// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoUBUXodsgDS0KMt-wVPjiKwrgh7dz230',
    appId: '1:750499933497:web:1686af293d12cc8b3c4ce8',
    messagingSenderId: '750499933497',
    projectId: 'nutrisense-xd',
    authDomain: 'nutrisense-xd.firebaseapp.com',
    storageBucket: 'nutrisense-xd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNBjrNL-0oJca1MnTXBzKS5CXDvLWLzBU',
    appId: '1:750499933497:android:22a371bff63c40c73c4ce8',
    messagingSenderId: '750499933497',
    projectId: 'nutrisense-xd',
    storageBucket: 'nutrisense-xd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlznM1kLXynYZAr43-emDB2ONnm8FVyBE',
    appId: '1:750499933497:ios:1cb12959c3c8df4a3c4ce8',
    messagingSenderId: '750499933497',
    projectId: 'nutrisense-xd',
    storageBucket: 'nutrisense-xd.firebasestorage.app',
    iosClientId: '750499933497-rpoj178k1df91gsp7lcm8iafnisr05or.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutrisense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlznM1kLXynYZAr43-emDB2ONnm8FVyBE',
    appId: '1:750499933497:ios:1cb12959c3c8df4a3c4ce8',
    messagingSenderId: '750499933497',
    projectId: 'nutrisense-xd',
    storageBucket: 'nutrisense-xd.firebasestorage.app',
    iosClientId: '750499933497-rpoj178k1df91gsp7lcm8iafnisr05or.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutrisense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoUBUXodsgDS0KMt-wVPjiKwrgh7dz230',
    appId: '1:750499933497:web:c0f38c02f9f29b613c4ce8',
    messagingSenderId: '750499933497',
    projectId: 'nutrisense-xd',
    authDomain: 'nutrisense-xd.firebaseapp.com',
    storageBucket: 'nutrisense-xd.firebasestorage.app',
  );
}
